### ISSUE TITLE
Customized ghast drops

### ISSUE THREAD

**Issue by PauMAVA** [PauMAVA/UhcPlugin#24]
Ghast drops should be customized via the config file.

The option should be as follows:
```
custom_ghast_drops:
    enabled: true
    item: gold_ingot # Minecraft item id.
    amount: 1 # Amount of the item
```

**Comment by PauMAVA** [comment]
If this feature is enabled ghast drops will be replaced by the specified drop. If the specified item type does not exist, ghasts will drop default ghast tears.
Default options are:
```
custom_ghast_drops:
    enabled: true
    item: gold_ingot # Minecraft item id.
    amount: 1 # Amount of the item
```
