### ISSUE TITLE
Implement skin changer functionalities for Online Mode

### ISSUE THREAD

**Issue by PauMAVA** [PauMAVA/UhcPlugin#9]
A proxy based Mojang API is needed to finish this feature

**Comment by andyvonde** [comment]
Yes, u need to implement that. And in offline mode too

**Comment by PauMAVA** [comment]
[Mojang API](https://github.com/PauMAVA/MojangAPI) implemented.

The feature will be introduced in the next release.

**Comment by PauMAVA** [comment]
The skin-changer is working correctly. The plugin is now broken due to player name changes on player disguising. Must replace all player name comparison checks by UUID checks. Opening #30 to track this issue.

Note that Offline Mode could have some issues with this feature as UUIDs might change on player's rejoin. Will add configuration on the next commit.

**Comment by PauMAVA** [comment]
Default config:
```
# If this feature is enabled all players will be randomly disguised with other participant's skin and names periodically
rotate_skins:
  enabled: true
  period: 2 # The period in episodes when a skin rotations cycle will be executed
```
Issue resolved.
